version: "2"
services:
  node:
    image: node
    ports: 
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080